Nextdoor/pg-bifrost

Dockerfile

https://github.com/golang/mock/commit/79d8603a659da203b11a30b9faeb999604924d86
We need to install this dependency manually if we want to install `mockgen` manually:
```We'll just let modules take care of keeping track of the deps.```

build - get golang.org/x/tools/go/packages explicitly

---

Dockerfile
README.md
itests/common.bash
itests/containers/data-poller/app/poller-kinesis.py
itests/docker-compose.yml
main/main.go
transport/progress/progress_tracker.go

This is better because files created in volumes by docker containers take the ownership permissions of the container's user/group (default `root`). This presents an issue when trying to clean-up those files from the host if that user isn't root (such as from CircleCI).

itests - use docker cp instead of vol & split out signal handling

---

transport/transporters/s3/transporter/transporter.go

```
0 [nehal@Nehals-Nextdoor-MacBook-Pro target] (nehal/s3-fix-aws-endpoint-code) $ PGHOST=localhost   PGPASSWORD=pgbifrost   CREATE_SLOT=true   BIFROST_S3_BUCKET=nehal-bifrost-test-bucket   AWS_REGION=us-west-1   WORKERS=2   ./pg-bifro
st replicate --create-slot s3
INFO[0000] Attempting to create a connection to localhost on 5432  package=conn
Replication slot 'pg_bifrost' already exists.
INFO[0000] Replicating to s3                             package=app
INFO[0000] replicationSlot=pg_bifrost                    package=app
INFO[0000] clientBufferSize=10000                        package=app
INFO[0000] whitelist=false                               package=app
INFO[0000] tablelist=[]                                  package=app
INFO[0000] partMethod=0 …
```

s3 - endpoint pointer - fix value check & override

---

transport/transporters/rabbitmq/transporter/transporter_test.go

- GetConnection() will be called at least 3 times.  Once for the initial setup,
once for the failure, and once again after the mock server is available again.
But if there's a slowdown, the third call might be repeated until the server is
actually available.
@nehalrp Does this fix issue #33 for you?

Fix race condition in rabbitmq transporter_test.go

---

transport/transporters/s3/transporter/transporter.go
transport/transporters/s3/transporter/transporter_test.go
utils/mocks/mock_timesource.go
utils/time.go

The intention was for this to more closely follow the time partitioning of firehose.

s3 transporter - change key partitioning to YYYY/MM/DD/HH

---

replication/client/client.go
replication/client/client_test.go

The unit tests did not previously properly shutdown the replication client go routine. This caused tests to panic because the client would continue work and perform "unexpected" actions.

Fix replication client unit test

---

replication/client/client.go
replication/client/client_test.go
transport/progress/progress_tracker.go

I discovered that we were creating a lock step problem. Our progress tracker was too aggressive at sleeping when it found no work to be done and our replication client was too aggressive backing off when there was back pressure.
What happened was was transports would all try to report work done but be blocked waiting up to 60ms. This would ultimately backup the replication client which would sleep for 2 seconds. When it was unblocked, there wold be a flood of data and the process would repeat.

Fix sleep timers to prevent needless backpressure

---

Gopkg.lock
Gopkg.toml
marshaller/marshaller.go

We're spending a lot of time doing json encoding and I'm hoping this will improve throughput.

replace built in json encoder with json-iterator

---

README.md

The envvar in README was incorrect.

Fix whitelist/blacklist regex documentation

---

replication/client/client.go
replication/client/client_test.go

Postgres requests a shutdown by insistently asking for a client heartbeat.

Handle shutdown

---

main/main.go
replication/client/conn/conn.go
utils/utils.go

Now that Go supports wrapping error natively, let's use it

main/main.go: fix a TODO related to better error handling

---

app/config/headers.go
app/runner.go
main/main.go
transport/batcher/batcher.go
transport/batcher/batcher_test.go
transport/factory/factory.go
transport/manager/manager.go

The batcher tick rate helps avoid CPU spin in pg-bifrost but it also artificially constrains the latency of bifrost as well. By exposing this setting we are able to attain lower latency writes.

add setting to control batcker tick rate

---

app/config/headers.go
main/main.go

Currently there is no way for pg-bifrost to pick up injected env variables for the dd host name. This specific use case comes up when working within a k8s environment where a datadog-operator injects an env variable that includes the host name information. 
This PR creates a new flag that pulls the dd host name from `DATADOG_AGENT_HOST` env var and the port from the `DATADOG_AGENT_PORT` env var (default value of the port is set to `8125`). These two values together are used to create the address of the dd agent. If the `DATADOG_AGENT_HOST` env _isn't_ populated, the service falls back on using the `DATADOG_HOST` as the address.
This change is backwards compatible with previous version. If it makes sense to do so, I can break backwards compatibility to have a cleaner implementation.

New env flag to route DD metrics to the dd agent on the host

---

main/main.go

Upon further inspection of the injected variable name into the container by the datadog-operator, the correct env var name to use is `DD_AGENT_HOST` and NOT `DATADOG_AGENT_HOST`.
This PR introduces a breaking change to fix forward.

Correct Datadog agent host env var name

---

replication/client/client.go
transport/batch/generic_batch.go
transport/batcher/batcher.go
transport/batcher/batcher_test.go
transport/transporters/s3/transporter/transporter.go
transport/transporters/s3/transporter/transporter_test.go

I've been investigating a performance difference between 1.5.0 and subsequent releases. I have a theory this has to do with memory allocations changing performance characteristics very slightly which lead to blocking and a backoff throttle being applied when workers are unable to keep up.

add metrics around blocking for tuning

---

marshaller/marshaller.go
marshaller/marshaller_test.go
stats/aggregator/aggregator.go

This PR decreases the number of memory allocations bifrost does by:
1.  re-using maps allocated during the marshaling processes. Note, for now I'm using `sync.Pool` which isn't super efficient and overkill for a single threaded usecase but it's quick dirty and keeps the code fairly clean.
2. adds a constant for formatted server time if the time is the epoch. Note, in practice we haven't seen this value ever be non-zero so I'm not sure if this is a library issue or if postgres never implemented this functionality.
3. I noticed the stats aggregator had a very expensive debug log call where we were formatting numbers prior to passing them to the logger. I'm a bit dubious of why we did it this way but for now I'm just wrapping the log line in a log level check.

decrease memory allocations

---

marshaller/marshaller.go

Decrease memory allocations done by the marshaller by re-using variables across executions. This change removes all repetitive allocations that our code does and the only remaining allocations are by the json library.

remove unnecessary allocations by the marshaller

---

app/runner.go
replication/client/client.go
replication/client/client_test.go

Previously if the replication client could not write a message downstream it went into a backoff loop where it would wait, try writing, and update progress if it was blocked. However, in practice this causes artificial delays. Instead I'm changing the flow control to be reliant on the downstream channel and if that's full then we periodically write progress via the a ticker we already use.
Just a note on the previous functionality, this also meant we were reading and sending progress way too often when blocked which limits the throughput as we're waiting on i/o.

remove backoff and rely simply on channel for flow control

---

marshaller/marshaller.go
marshaller/marshaller_test.go

The marshaller is doing unnecessary work processing these messages and they get discarded by the batcher because begin/commit messages are not passed downstream.

don't marshall begin or commit messages

---

app/runner.go
docker-compose.yml
marshaller/marshaller.go
transport/batcher/batcher.go
transport/batcher/batcher_test.go
transport/factory/factory.go
transport/manager/manager.go
transport/progress/progress_tracker.go
transport/progress/progress_tracker_test.go

Originally txn seen progress was sent to the progress tracker via an unbuffered channel every time we saw a `commit` message. The use of the unbuffered channel ensured we always recorded seen txns before written txns. However, this creates a bottleneck in high throughput configurations.
The change I'm making keeps the end functionality the same but instead of reporting seen txns ever time we only report progress right before flushing a batch to the transporters. By batching up the progress we avoid the overhead of frequent synchronization between batcher and progress tracker.

send seen progress in batches

---

replication/message.go

Previously the servertime of a replicated message was not transmitted in older versions of postgres. When we upgraded to a newer version we didn't bother checking if it worked. It does, but we had 2 bugs here 1) we used `Seconds()` which provides the second component of the timestamp (0-59) versus the posix time. 2) the conversion function later on expected time in milliseconds instead of seconds so this would have been broken anyway.

fix servertime bug

---

itests/common.bash
marshaller/marshaller.go
marshaller/marshaller_test.go

This PR adds two new fields to the output JSON to help with tracking and debugging.
`time_ms`: time in ms of the server time for the record. This was added because `time` is encoded in `RFC3339` which drops millisecond precision. For compatibility both fields remain. `time_ms` is encoded as a json number.
`txn`: this is the record's transaction id combined with the nanosecond timestamp of when bifrost saw the transaction from the WAL. This is encoded in a string of `<txn id>-<ns timestamp>`. The timestamp helps determine if bifrost re-read a transaction.

add time ms and txn to encoded json
